services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./app/public:/var/www/html
    networks:
      - trancendence
    expose:
      - "9000"
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    volumes:
      - ./app/public:/var/www/html
      - ./docker/nginx/conf/default:/etc/nginx/conf.d/default.conf:ro
    networks:
      - trancendence
    ports:
      - "8080:80"
    depends_on:
      - php

networks:
  trancendence:
    driver: bridge