services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./app/public:/var/www/html
    networks:
      - trancendence
    expose:
      - "9000"
  websocket:
    build:
      context: .
      dockerfile: docker/websocket/Dockerfile
    container_name: websocket
    volumes:
      - ./app/backend:/var/www/backend
    networks:
      - trancendence
    ports:
      - "8081:8080"
    command: php /var/www/backend/server.php
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    volumes:
      - ./app/public:/var/www/html
      - ./docker/nginx/conf/default:/etc/nginx/conf.d/default.conf:ro
    networks:
      - trancendence
    ports:
      - "8080:80"
    depends_on:
      - php
      - websocket

networks:
  trancendence:
    driver: bridge